using AutomationExercise.Tests.Fixtures;
using AutomationExercise.Tests.Helpers;
using AutomationExercise.Tests.Pages;
using NUnit.Framework;

namespace AutomationExercise.Tests.Tests;

[TestFixture]
[Category("Regression")]
public class TCVA06_ContactUsFileUpload : BaseTest
{
    [Test]
    [Description("TC-VA-06: Contact-Us form with file upload — submits successfully and shows the success message")]
    public async Task ContactUs_WithFileUpload_ShouldShowSuccessMessage()
    {
        var user = TestDataFactory.GenerateUser();
        var uploadPath = Path.Combine(AppContext.BaseDirectory, "TestData", "sample-upload.txt");

        var contactUs = new ContactUsPage(Page);

        await contactUs.NavigateAsync();
        await contactUs.VerifyGetInTouchVisibleAsync();

        await contactUs.FillContactFormAsync(
            name: user.Name,
            email: user.Email,
            subject: "Automated QA Test — Upload Verification",
            message: "This submission is generated by an automated test. Please disregard.");

        await contactUs.UploadFileAsync(uploadPath);
        await contactUs.SubmitFormAsync();
        await contactUs.VerifySuccessMessageVisibleAsync();
    }
}
